language: common-lisp
sudo: false

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - SUCCESS_RESULT=0
    - ERROR_RESULT=1
  matrix:
    - LISP=ccl-bin

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh
  - ros install lisp-unit

script:
  - ros -e '(uiop:quit $SUCCESS_RESULT)'
